# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.7"

python:
  install:
    - requirements: requirements.txt
    - method: setuptools
      path: .

sphinx:
  configuration: docs/conf.py
