coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
        flags:
          - unit
        paths:
          - "dropbox"
        branches:
          - master
        if_not_found: success
        if_ci_failed: error
        informational: true
        only_pulls: false