codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "0...100"
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0%
        base: auto
        flags:
          - unit
        paths:
          - "dropbox"
        # advanced
        branches:
          - master
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false