[tox]

envlist = py{311,312,313,py3},check,lint,docs,test_unit,coverage
skip_missing_interpreters = true


[testenv:test_integration]

commands =
    pytest test/integration/

passenv =
    DROPBOX_REFRESH_TOKEN
    DROPBOX_APP_KEY
    DROPBOX_APP_SECRET
    DROPBOX_DOMAIN
    DROPBOX_TEAM_TOKEN
    DROPBOX_TOKEN
    DROPBOX_WEB_HOST
    DROPBOX_SHARED_LINK

deps =
    pip
    -rtest/requirements.txt

[testenv:check]

commands =
    python -m build
    twine check dist/*

deps =
    build
    twine

usedevelop = true


[testenv:lint]
description = check code with Ruff
commands =
    ruff check dropbox example test
    ruff format --check dropbox example test
deps =
    ruff
    -rtest/requirements.txt

usedevelop = true

[testenv:coverage]

commands =
    coverage run --rcfile=.coveragerc -m pytest test/unit/test_dropbox_unit.py
    coverage report

deps =
    -rtest/requirements.txt

[testenv:codecov]

commands =
    coverage run --rcfile=.coveragerc -m pytest test/unit/test_dropbox_unit.py
    coverage xml

deps =
    -rtest/requirements.txt

[testenv:test_unit]

commands =
    pytest test/unit/

deps =
    -rtest/requirements.txt

[testenv:docs]
description = invoke sphinx-build to build the HTML docs
extras = docs
commands = sphinx-build -b html docs build/html
deps =
    sphinx
