# -*- coding: utf-8 -*-
# Auto-generated by Stone, do not modify.
# @generated
# flake8: noqa
# pylint: skip-file
from __future__ import unicode_literals
from stone.backends.python_rsrc import stone_base as bb
from stone.backends.python_rsrc import stone_validators as bv


class ContainsDbidAnnotation(bb.AnnotationType):
    """
    Annotation type should be applied to Response object fields which contain
    account id
    """

    __slots__ = [
        "_authorize_caller",
    ]

    def __init__(self, authorize_caller=True):
        self._authorize_caller = authorize_caller

    @property
    def authorize_caller(self):
        """
        :rtype: bool
        """
        return self._authorize_caller


ROUTES = {}
