name: Publish CodeCov

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.x]

    steps:
    - uses: actions/checkout@v2
    - name: Publish CodeCov
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install codecov pytest coverage
    - name: Run Coverage
      run: |
        coverage run --rcfile=.coveragerc -m pytest test/test_dropbox_unit.py
        coverage xml
    - name: Codecov
      uses: codecov/codecov-action@v1.0.13
      with:
        file: ./coverage.xml
        flags: unittests
        env_vars: OS,PYTHON
        fail_ci_if_error: true
