name: Spec Update
on:
  workflow_dispatch:
  repository_dispatch:
    types: [spec_update]

permissions:
  id-token: write
  contents: read

jobs:
  spec-update:
    uses: cguldner/sdk-build-tools/.github/workflows/spec-update.yml@master
    with:
      python-version: '3.11'
      submodule-path: spec
      base-branch: main
      merge-method: squash
